SHOW DATABASES;

CREATE DATABASE join_test;

CREATE TABLE Table_A (
  PK INT,
  Value VARCHAR(25)
);

SHOW TABLES;

CREATE TABLE Table_B (
  PK INT,
  Value VARCHAR(25)
);

INSERT INTO Table_A VALUES (1, "FOX");
INSERT INTO Table_A VALUES (2, "COP");
INSERT INTO Table_A VALUES (3, "TAXI");
INSERT INTO Table_A VALUES (4, "LINCION");
INSERT INTO Table_A VALUES (5, "ARIZONA");
INSERT INTO Table_A VALUES (6, "WASHINGTON");
INSERT INTO Table_A VALUES (7, "DELL");
INSERT INTO Table_A VALUES (10, "LUCENT");

SELECT * FROM Table_A;

INSERT INTO Table_B VALUES (1, "TROT");
INSERT INTO Table_B VALUES (2, "CAR");
INSERT INTO Table_B VALUES (3, "CAB");
INSERT INTO Table_B VALUES (6, "MONUMENT");
INSERT INTO Table_B VALUES (7, "PC");
INSERT INTO Table_B VALUES (8, "MICROSOFT");
INSERT INTO Table_B VALUES (9, "APPLE");
INSERT INTO Table_B VALUES (11, "SCOTCH");

SELECT * FROM Table_B;

# INNER JOIN
SELECT A.PK AS A_PK, B.PK AS B_PK,
    A.Value AS A_Value, B.Value AS B_Value
FROM Table_A A
INNER JOIN Table_B B
ON A.PK = B.PK;

# LEFT JOIN
SELECT A.PK AS A_PK, B.PK AS B_PK,
    A.Value AS A_Value, B.Value AS B_Value
FROM Table_A A
LEFT JOIN Table_B B
ON A.PK = B.Pk;

# RIGHT JOIN
SELECT A.PK AS A_PK, B.PK AS B_PK,
    A.Value AS A_Value, B.Value AS B_Value
FROM Table_A A
RIGHT JOIN Table_B B
ON A.PK = B.PK;

# FULL OUTER JOIN
SELECT *
FROM Table_A
LEFT JOIN Table_B
ON Table_A.PK = Table_B.PK
UNION ALL
SELECT *
FROM Table_A
RIGHT JOIN Table_B
ON Table_A.PK = Table_B.PK
WHERE Table_A.PK IS NULL;

# LEFT JOIN EXCLUDING INNER JOIN
SELECT A.PK AS A_PK, B.PK AS B_PK, A.Value AS A_Value, B.Value AS B_Value
FROM Table_A AS A
LEFT JOIN Table_B AS B
ON A.PK = B.PK
WHERE B.PK IS NULL;

# RIGHT JOIN EXCLUDING INNER JOIN
SELECT A.PK AS A_PK, B.PK AS B_PK, A.Value AS A_Value, B.Value AS B_Value
FROM Table_A AS A
RIGHT JOIN Table_B AS B
ON A.PK = B.PK
WHERE A.PK IS NULL;

# FULL OUTER JOIN EXCLUDING INNER JOIN
SELECT *
FROM Table_A
LEFT JOIN Table_B
ON Table_A.PK = Table_B.PK
WHERE Table_B.PK IS NULL
UNION ALL
SELECT *
FROM Table_A
RIGHT JOIN Table_B
ON Table_A.PK = Table_B.PK
WHERE Table_A.PK is NULL;